CC=gcc
ARGS=-Wall -Werror

q4: q4.c
	$(CC) q4.c $(ARGS) -o q4

q5: q5.c
	$(CC) q5.c $(ARGS) -o q5

Coord: Coord.c
	$(CC) Coord.c $(ARGS) -o Coord

Queue: Queue.c Queue.h
	$(CC) Queue.c $(ARGS) -o Queue

clean:
	rm q4 q5 Coord Queue
